name: hilchot_avelut
description: "A book of laws of mourning"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+2

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # State Management
  provider: ^6.1.1

  # WebView for HTML display
  webview_flutter: ^4.4.2

  # PDF Viewer
  syncfusion_flutter_pdfviewer: ^31.2.16

  # URL Launcher for email
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.2

flutter:


  uses-material-design: true
  assets:
    - assets/html/
    - assets/html/chapter_1/
    - assets/html/chapter_2/
    - assets/html/chapter_3/
    - assets/html/chapter_4/
    - assets/html/chapter_5/
    - assets/html/chapter_7/
    - assets/html/chapter_8/
    - assets/html/chapter_9/
    - assets/html/terms/
    - assets/pdf/book.pdf
    - assets/book.png
    - assets/book_full.png
    - assets/privacyPolicy.html

  fonts:
    - family: David
      fonts:
        - asset: assets/fonts/DavidLibre-Regular.ttf
        - asset: assets/fonts/DavidLibre-Bold.ttf
          weight: 700


flutter_native_splash:
  android: true
  ios: true
  color: "#ffffff"
  image: "assets/book.png"

  android_12:
    color: "#ffffff"
    image: "assets/book.png"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/book.png"
  remove_alpha_ios: true

